/* eslint-disable */

const charTalents = [
  undefined, // Level 0
  undefined, // Level 1
  {
    'level': 2,
    'talentBooksRarity': 2,
    'talentBooks': 3,
    'commonMaterialsRarity': 1,
    'commonMaterials': 6,
    'weeklyBossMaterial': 0,
    'mora': 12500,
    'crown': false,
  },
  {
    'level': 3,
    'talentBooksRarity': 3,
    'talentBooks': 2,
    'commonMaterialsRarity': 2,
    'commonMaterials': 3,
    'weeklyBossMaterial': 0,
    'mora': 17500,
    'crown': false,
  },
  {
    'level': 4,
    'talentBooksRarity': 3,
    'talentBooks': 4,
    'commonMaterialsRarity': 2,
    'commonMaterials': 4,
    'weeklyBossMaterial': 0,
    'mora': 25000,
    'crown': false,
  },
  {
    'level': 5,
    'talentBooksRarity': 3,
    'talentBooks': 6,
    'commonMaterialsRarity': 2,
    'commonMaterials': 6,
    'weeklyBossMaterial': 0,
    'mora': 30000,
    'crown': false,
  },
  {
    'level': 6,
    'talentBooksRarity': 3,
    'talentBooks': 9,
    'commonMaterialsRarity': 2,
    'commonMaterials': 9,
    'weeklyBossMaterial': 0,
    'mora': 37500,
    'crown': false,
  },
  {
    'level': 7,
    'talentBooksRarity': 4,
    'talentBooks': 4,
    'commonMaterialsRarity': 3,
    'commonMaterials': 4,
    'weeklyBossMaterial': 1,
    'mora': 120000,
    'crown': false,
  },
  {
    'level': 8,
    'talentBooksRarity': 4,
    'talentBooks': 6,
    'commonMaterialsRarity': 3,
    'commonMaterials': 6,
    'weeklyBossMaterial': 1,
    'mora': 260000,
    'crown': false,
  },
  {
    'level': 9,
    'talentBooksRarity': 4,
    'talentBooks': 12,
    'commonMaterialsRarity': 3,
    'commonMaterials': 9,
    'weeklyBossMaterial': 2,
    'mora': 450000,
    'crown': false,
  },
  {
    'level': 10,
    'talentBooksRarity': 4,
    'talentBooks': 16,
    'commonMaterialsRarity': 3,
    'commonMaterials': 12,
    'weeklyBossMaterial': 2,
    'mora': 700000,
    'crown': true,
  },
];

module.exports = charTalents;