const charAscensions = {
  'ascensionOne': {
    'levelRequired': 20,
    'ascensionGemsRarity': 2,
    'ascensionGems': 1,
    'eliteBossMaterials': 0,
    'commonMaterialsRarity': 1,
    'commonMaterials': 3,
    'localSpecialities': 3,
    'mora': 20000,
  },
  'ascensionTwo': {
    'levelRequired': 40,
    'ascensionGemsRarity': 3,
    'ascensionGems': 3,
    'eliteBossMaterials': 2,
    'commonMaterialsRarity': 1,
    'commonMaterials': 15,
    'localSpecialities': 10,
    'mora': 40000,
  },
  'ascensionThree': {
    'levelRequired': 50,
    'ascensionGemsRarity': 3,
    'ascensionGems': 6,
    'eliteBossMaterials': 4,
    'commonMaterialsRarity': 2,
    'commonMaterials': 12,
    'localSpecialities': 20,
    'mora': 60000,
  },
  'ascensionFour': {
    'levelRequired': 60,
    'ascensionGemsRarity': 4,
    'ascensionGems': 3,
    'eliteBossMaterials': 8,
    'commonMaterialsRarity': 2,
    'commonMaterials': 18,
    'localSpecialities': 30,
    'mora': 80000,
  },
  'ascensionFive': {
    'levelRequired': 70,
    'ascensionGemsRarity': 4,
    'ascensionGems': 6,
    'eliteBossMaterials': 12,
    'commonMaterialsRarity': 3,
    'commonMaterials': 12,
    'localSpecialities': 45,
    'mora': 100000,
  },
  'ascensionSix': {
    'levelRequired': 80,
    'ascensionGemsRarity': 5,
    'ascensionGems': 6,
    'eliteBossMaterials': 20,
    'commonMaterialsRarity': 3,
    'commonMaterials': 24,
    'localSpecialities': 60,
    'mora': 120000,
  },
};

module.exports = charAscensions;