const weaponAscensions = {
  'oneStar': {
    'ascensionOne': {
      'levelRequired': 20,
      'weaponMaterialsRarity': 2,
      'weaponMaterials': 1,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 1,
      'commonMaterialsRarity': 1,
      'commonMaterials': 1,
      'mora': 0,
    },
    'ascensionTwo': {
      'levelRequired': 40,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 1,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 4,
      'commonMaterialsRarity': 1,
      'commonMaterials': 2,
      'mora': 5000,
    },
    'ascensionThree': {
      'levelRequired': 50,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 2,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 2,
      'commonMaterialsRarity': 2,
      'commonMaterials': 2,
      'mora': 5000,
    },
    'ascensionFour': {
      'levelRequired': 60,
      'weaponMaterialsRarity': 4,
      'weaponMaterials': 1,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 4,
      'commonMaterialsRarity': 2,
      'commonMaterials': 3,
      'mora': 10000,
    },
  },
  'twoStar': {
    'ascensionOne': {
      'levelRequired': 20,
      'weaponMaterialsRarity': 2,
      'weaponMaterials': 1,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 1,
      'commonMaterialsRarity': 1,
      'commonMaterials': 1,
      'mora': 5000,
    },
    'ascensionTwo': {
      'levelRequired': 40,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 1,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 5,
      'commonMaterialsRarity': 1,
      'commonMaterials': 4,
      'mora': 5000,
    },
    'ascensionThree': {
      'levelRequired': 50,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 3,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 3,
      'commonMaterialsRarity': 2,
      'commonMaterials': 3,
      'mora': 10000,
    },
    'ascensionFour': {
      'levelRequired': 60,
      'weaponMaterialsRarity': 4,
      'weaponMaterials': 1,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 5,
      'commonMaterialsRarity': 2,
      'commonMaterials': 4,
      'mora': 15000,
    },
  },
  'threeStar': {
    'ascensionOne': {
      'levelRequired': 20,
      'weaponMaterialsRarity': 2,
      'weaponMaterials': 2,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 2,
      'commonMaterialsRarity': 1,
      'commonMaterials': 1,
      'mora': 5000,
    },
    'ascensionTwo': {
      'levelRequired': 40,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 2,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 8,
      'commonMaterialsRarity': 1,
      'commonMaterials': 5,
      'mora': 10000,
    },
    'ascensionThree': {
      'levelRequired': 50,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 4,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 4,
      'commonMaterialsRarity': 2,
      'commonMaterials': 4,
      'mora': 15000,
    },
    'ascensionFour': {
      'levelRequired': 60,
      'weaponMaterialsRarity': 4,
      'weaponMaterials': 2,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 8,
      'commonMaterialsRarity': 2,
      'commonMaterials': 6,
      'mora': 20000,
    },
    'ascensionFive': {
      'levelRequired': 70,
      'weaponMaterialsRarity': 4,
      'weaponMaterials': 4,
      'eliteMaterialsRarity': 4,
      'eliteMaterials': 6,
      'commonMaterialsRarity': 3,
      'commonMaterials': 4,
      'mora': 25000,
    },
    'ascensionSix': {
      'levelRequired': 80,
      'weaponMaterialsRarity': 5,
      'weaponMaterials': 3,
      'eliteMaterialsRarity': 4,
      'eliteMaterials': 12,
      'commonMaterialsRarity': 3,
      'commonMaterials': 8,
      'mora': 30000,
    },
  },
  'fourStar': {
    'ascensionOne': {
      'levelRequired': 20,
      'weaponMaterialsRarity': 2,
      'weaponMaterials': 3,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 3,
      'commonMaterialsRarity': 1,
      'commonMaterials': 2,
      'mora': 5000,
    },
    'ascensionTwo': {
      'levelRequired': 40,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 3,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 12,
      'commonMaterialsRarity': 1,
      'commonMaterials': 8,
      'mora': 15000,
    },
    'ascensionThree': {
      'levelRequired': 50,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 6,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 6,
      'commonMaterialsRarity': 2,
      'commonMaterials': 6,
      'mora': 20000,
    },
    'ascensionFour': {
      'levelRequired': 60,
      'weaponMaterialsRarity': 4,
      'weaponMaterials': 3,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 12,
      'commonMaterialsRarity': 2,
      'commonMaterials': 9,
      'mora': 30000,
    },
    'ascensionFive': {
      'levelRequired': 70,
      'weaponMaterialsRarity': 4,
      'weaponMaterials': 6,
      'eliteMaterialsRarity': 4,
      'eliteMaterials': 9,
      'commonMaterialsRarity': 3,
      'commonMaterials': 6,
      'mora': 35000,
    },
    'ascensionSix': {
      'levelRequired': 80,
      'weaponMaterialsRarity': 5,
      'weaponMaterials': 4,
      'eliteMaterialsRarity': 4,
      'eliteMaterials': 18,
      'commonMaterialsRarity': 3,
      'commonMaterials': 12,
      'mora': 45000,
    },
  },
  'fiveStar': {
    'ascensionOne': {
      'levelRequired': 20,
      'weaponMaterialsRarity': 2,
      'weaponMaterials': 5,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 5,
      'commonMaterialsRarity': 1,
      'commonMaterials': 3,
      'mora': 10000,
    },
    'ascensionTwo': {
      'levelRequired': 40,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 5,
      'eliteMaterialsRarity': 2,
      'eliteMaterials': 18,
      'commonMaterialsRarity': 1,
      'commonMaterials': 12,
      'mora': 20000,
    },
    'ascensionThree': {
      'levelRequired': 50,
      'weaponMaterialsRarity': 3,
      'weaponMaterials': 9,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 9,
      'commonMaterialsRarity': 2,
      'commonMaterials': 9,
      'mora': 30000,
    },
    'ascensionFour': {
      'levelRequired': 60,
      'weaponMaterialsRarity': 4,
      'weaponMaterials': 5,
      'eliteMaterialsRarity': 3,
      'eliteMaterials': 18,
      'commonMaterialsRarity': 2,
      'commonMaterials': 14,
      'mora': 45000,
    },
    'ascensionFive': {
      'levelRequired': 70,
      'weaponMaterialsRarity': 4,
      'weaponMaterials': 9,
      'eliteMaterialsRarity': 4,
      'eliteMaterials': 14,
      'commonMaterialsRarity': 3,
      'commonMaterials': 9,
      'mora': 55000,
    },
    'ascensionSix': {
      'levelRequired': 80,
      'weaponMaterialsRarity': 5,
      'weaponMaterials': 6,
      'eliteMaterialsRarity': 4,
      'eliteMaterials': 27,
      'commonMaterialsRarity': 3,
      'commonMaterials': 18,
      'mora': 65000,
    },
  },
};

module.exports = weaponAscensions;